### ISSUE TITLE
cannot upload image in admin if PHP open_basedir is active

### ISSUE THREAD

**Issue by Cerdic** [thelia/thelia#2176]
```open_basedir``` allow to isolate website from each other on same server, blocking PHP file parsing outside directories set in vhost configuration.

Uploaded file are stored uin temporary file in ```upload_tmp_dir``` and should be moved with the PHP function ```move_uploaded_file``` (http://php.net/manual/fr/function.move-uploaded-file.php) that is the only one allowed to access a temporary file outside ```open_basedir```.

Thelia (through Symphony) try to access directly to the temporary file which cause a Fatal Error :

```
[Fri Jun 03 16:57:22.593972 2016] [:error] [pid 6853] [client xxx] PHP Fatal error:  Uncaught exception 'Symfony\\Component\\HttpFoundation\\File\\Exception\\FileNotFoundException' with message 'The file "/home/tmp/phpxyKFSE" does not exist' in /home/.../public_html/vendor/symfony/http-foundation/File/File.php:37\nStack trace:\n#0 /home/.../public_html/vendor/symfony/http-foundation/File/UploadedFile.php(96): Symfony\\Component\\HttpFoundation\\File\\File->__construct('/home/tmp/phpxy...', true)\n#1 /home/.../public_html/vendor/symfony/http-foundation/FileBag.php(89): Symfony\\Component\\HttpFoundation\\File\\UploadedFile->__construct('/home/tmp/phpxy...', 'import- m\\xC3\\xA9cani...', 'application/vnd...', 1712, 0)\n#2 [internal function]: Symfony\\Component\\HttpFoundation\\FileBag->convertFileInformation(Array)\n#3 /home/.../public_html/vendor/symfony/http-foundation/FileBag.php(92): array_map(Array, Array)\n#4 /home/.../public_html/vendor/symfony/http-foundation/FileBag.php( in /home/.../public_html/vendor/symfony/http-foundation/File/File.php on line 37, referer: http://www.example.fr/admin/import
```

**Comment by anoziere** [comment]
Tracing the stack trace: the failure happens inside `Symfony\Component\HttpFoundation\FileBag::convertFileInformation()`, which builds an `UploadedFile` for every submitted file while the Request object is constructed, before Thelia's router or any controller code runs. `UploadedFile` extends `File`, whose constructor calls PHP's `is_file()` on the upload's temporary path, and `is_file()` is restricted by `open_basedir`, unlike `move_uploaded_file()`, which PHP explicitly exempts from that restriction.

So this doesn't happen in Thelia's own upload handling: there is no Thelia code between the raw PHP upload and this check, which means there is no Thelia-side fix. It's a known constraint of `open_basedir` isolation with any Symfony application: the directory PHP uses for upload temp files (the `upload_tmp_dir` ini setting, or the system temp dir if unset) has to be included in `open_basedir`, otherwise this exception is unavoidable regardless of the application on top.

Since this is a hosting/PHP configuration requirement rather than an application bug, and the report predates several major PHP/Symfony upgrades, we're closing it. If you can reproduce it on a current Thelia version with `upload_tmp_dir` correctly included in `open_basedir`, please reopen with the setup details.
